### ISSUE TITLE
Disappointing

### ISSUE THREAD

**Issue by MLpit123** [teuteuf/worldle#101]
An uninhabited Norwegian territory? Is anyone actually getting these? Game used to be good, several of the last ones are remote and not real countries. Please resume choosing one of the vast myriad of real nations on our planet, before I and several others, I'm sure, check out of this game.

**Comment by Tiv0w** [comment]
Every puzzle choice is taken from the [ISO_3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) list. This includes not only countries but also some territories.
If you click the interrogation mark, you'll see that "each guess must be a valid **country, territory, ...**". Plus the input box clearly indicates that the guess could be a territory.

I'm sorry but this game exactly provides what it advertises for.

As a personal note, I'd argue that it's for the better, because it helps you learn about new things. If you want to create COUNTRYDLE, go for it, or you could also propose a PR with the possibility to only have the UN recognized countries.
