### ISSUE TITLE
Today’s country is NOT a country!!!

### ISSUE THREAD

**Issue by missmadmolly** [teuteuf/worldle#105]
Bouvet Island is an uninhabited Norwegian Island - NOT its own country! It is technically a part of Norway and is one of the most remote islands in the world. It would be nearly impossible for someone to correctly guess this answer - it should be removed from random selection for Worldle.

**Comment by HSchmale16** [comment]
Agreed! It was completely unlabeled when I was looking on google maps for the island and using measure distance.

**Comment by Tiv0w** [comment]
Every puzzle choice is taken from the [ISO_3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) list. This includes not only countries but also some territories.
If you click the interrogation mark, you'll see that "each guess must be a valid **country, territory, ...**". Plus the input box clearly indicates that the guess could be a territory.

This game exactly provides what it advertises for.

As a personal note, I'd argue that it's for the better, because it helps you learn about new things. If you want a restricted set of countries, you should either create your own COUNTRYDLE (maybe fork the project), or you could also propose a PR with the possibility to switch in a clear manner to a restricted list.

Last point, a game being difficult for many people doesn't make it less interesting or mean it should be eased. Many people love the difficulty of the Dark Souls games, but at least as many don't like it.
