### ISSUE TITLE
Every country should be north of Antarctica

### ISSUE THREAD

**Issue by kegelkugel** [teuteuf/worldle#126]
When Antarctica is entered as a guess (and Antarctica is not the right answer), then the direction arrow should always point straight North ⬆️. Currently, the arrow can also point in other directions like northeast ↗️, which I would consider incorrect or – at least – not helpful. Similarly, when Antarctica is the right answer, then for any other guess, the direction arrow should point straight South ⬇️.

I suggest to use as coordinates for Antarctica the South Pole with latitude -90° and no longitude (or 0° if a number must be used). This appears to me to be a natural choice of the coordinates of Antarctica and it should ensure that the direction arrow will always point straight North from Antarctica to any other country, territory, etc.

The following screenshot of today shows Antarctica as a wrong guess with a direction arrow not pointing straight North:

![Screenshot_20220321-161916~2](https://user-images.githubusercontent.com/29691621/159293065-6e5f1cc8-b080-42ab-b183-2ae33d68ebda.png)

**Comment by Sun8908** [comment]
I think South Pole and Antarctica are two concepts. Antarctica is a continent and the centre of gravity of the continent is unlikely to be the South Pole. I can't find any resources from the Internet talking about the coordinates of the centre of gravity though. The current coordinates used now to compute the distances (-75.250973,-0.071389)  seem fine to me.
But the arrows can definitely be changed.

**Comment by kegelkugel** [comment]
I agree, Antarctica is different from the South Pole.  The South Pole is a point that lies centrally in Antarctica.  Therefore, I think the South Pole would be a useful centre point for Antarctica in Worldle, even if it is not the exact centre of gravity of the Antarctic continent.  The South Pole is naturally associated with the continent, lies near its centre, and has very simple coordinates.

Looking at maps like the one below, I doubt that 75°S, 0.07°W is the centre of gravity of Antarctica.  This point is just below the "e" of "Queen Maud Land" on this map:
![Map of Antarctica](https://worldmapblank.com/wp-content/uploads/2021/02/Antarctica-Map-with-Cities-Labeled.jpg)

**Comment by gamesaucer** [comment]
I have a guess for how these (frankly quite unreasonable) coordinates were derived, though, and why it's likely only Antarctica that's broken as a result.

My guess is that the International Date Line is throwing things into disarray. The way the canonical coordinates were probably calculated by first unwrapping the globe to some 2D representation, which would turn Antarctica into a band along the bottom. This would place the longitude close to 0°, because land is fairly evenly distributed on both sides. Also, because this places the south pole at the "bottom" of the country and the coast at the "top", its "centre" would be somewhere in between the south pole and the coast, probably more towards the coast since the Antarctic Peninsula and Wilkes Land put a decent amount of landmass north of where the Antarctic Coast lies on 0° longitude.

This isn't a very intuitive or transparent way to derive the centre of Antarctica tbh. A point near the coast of Queen Maud Land is not a position any reasonable player would guess counts as the "centre point" unless they already know the list of coordinates the game uses ahead of time.

It seems that the list of coordinates that was chosen just isn't very well suited to this game for Antarctica in particular for this reason. I guess it makes sense since the list wasn't compiled _for_ this game, so changing it to a more reasonable location is a very sensible suggestion, even if I disagree that that location should exactly be the South Pole.

**Comment by kegelkugel** [comment]
Your explanation makes a lot of sense to me, sounds all correct. So I guess we agree that it makes sense to change the centre point of Antarctica. It's also fine with me to put it at some position different from the South Pole. In this case, we need to come up with a better way of calculating the centre of the southernmost continent.
