### ISSUE TITLE
Scale

### ISSUE THREAD

**Issue by 22out17** [teuteuf/worldle#129]
Thank you for the game, love to playing it.
I'd like to suggest you too place a scale on the side of the featured country it's an important tool in maps. ;)

**Comment by teuteuf** [comment]
Hello!

I don't fix I'll add a scale on the image, because I think it's a fun part of the game to get tricked by the unknown size of the map.

But I've planed to allow to replace proximity percent by a scale percent, which will help to estimate the country size comparing to other guess.

Should do it soon! :)

You can keep track of this here: https://github.com/teuteuf/worldle/issues/9

**Comment by teuteuf** [comment]
I've added a a settings to replace proximity by size percent.

If the country you input is twice the size of the target: it will display 200%!
If the country you input is half the size of the target: it will display 50%...
