### ISSUE TITLE
Outline not matching territory

### ISSUE THREAD

**Issue by stueynz** [teuteuf/worldle#142]
https://en.m.wikipedia.org/wiki/Kerguelen_Islands  Is not the whole of https://en.m.wikipedia.org/wiki/French_Southern_and_Antarctic_Lands

Showing the outline of Kerguelen Islands for the Southern & Antarctic lands is not fair.

**Comment by gamesaucer** [comment]
I concur, I came here to report the same issue. The outline shown was only Kerguelen, and yet Kerguelen is not an answer the game recognises or is even contained in the correct answer. Either the answer should have been "Kerguelen Islands" or the outline should have included the Crozet Islands.

**Comment by MetalManiacMc** [comment]
+ all the islands around Madagascar and maybe even the Adelie Land
But it was guessable because the island is visible on the map

**Comment by gamesaucer** [comment]
>   But it was guessable because the island is visible on the map

Disagree, for multiple reasons:

1. Not all maps contain "French Southern and Antarctic Lands". Depending on the map you use, the territory might simply be listed as "Kerguelen (Fr)". Having to use a particular map to get to an answer the game deems acceptable seems unreasonable to me. And indeed the map I use just lists "Kerguelen", which was exceedingly unhelpful, and having studied it beforehand did not help me.
2. Not all players like to use a map. I personally like to use my existing geographical knowledge to deduce the answer, and perhaps learn a thing or two in the process. I'm not just playing "Where's Waldo" on a globe. I knew the name of the archipelago was Kerguelen thanks to doing some research after the last time that I couldn't find an island in the world's southern oceans, and yet the only way I was able to get to the answer was because I knew which country the territory was a part of, since the correct result showed up in the list after typing "French". So even though I knew the name of the landmass shown on screen, I was led to the answer by something completely unrelated. Not all territories have the name of their country in them (e.g. South Georgia, although for that one the name _would_ have helped me).

I think that ultimately the solution to this and related issues is to accept other answers that just a single canonical name, e.g. make typing "Kerguelen" show "French Southern and Antarctic Lands" in the filtered list, because you've correctly identified the landmass shown, which I think should be enough to qualify you for getting a win, even if you didn't know the exact canonical name the game uses for this target.

That's just my view on the matter though. Of course you're free to play the game however you want, but in this particular case I was a bit annoyed by how strict the answer was, especially when it didn't fully match the outline shown. I think that a game should make the player feel clever for showing off their knowledge, not confuse and annoy them with needless and hard to predict nitpickery.

If you have further reasons to disagree with what I've said above, I'd of course be happy to hear them as well. Game design definitely isn't a simple black-and-white matter after all.

**Comment by gamesaucer** [comment]
Just as an example, I would have found a shape like this much more helpful as an indication that "Kerguelen" is not the answer.
![image](https://user-images.githubusercontent.com/2377751/160302492-020110af-4fb6-4651-9921-1a0be81e42b8.png)

**Comment by teuteuf** [comment]
Name updated to be more explicit.
