### ISSUE TITLE
changing country

### ISSUE THREAD

**Issue by tenormichaelk** [teuteuf/worldle#160]
my granddaughter and I played yesterday morning (4/1 EDT) and the answer was Norfolk Island (a very tiny island-we did not find it). By evening the game says the answer is Niger. Very confused, was this an April Fools version?

**Comment by PromptServiceNZ** [comment]
There’s a bit of this going on. Someone’s already asked a similar question from 5 days ago when Australia and another country can up in different browsers. 
And today I correctly guessed USA (surprise, surprise) but my wife got Tanzania to guess and when I went to show her mine- my correct guess was still showing but now it was below a silhouette of…Tanzania.

**Comment by teuteuf** [comment]
Hello!

Your app has been updated after you input your guess... That's why you got this weird behavior.

Good news, it also means you're now running an updated version of the code, so it should not happen anymore!

Also, I've made some fix on how to handle code updates and cache refresh, it should work better next time I do changes on the app!

Sorry for the inconvenience!

**Comment by PromptServiceNZ** [comment]
No, that’s all good. Just feedback. Thank YOU. 

Steve King +64275643813

**Comment by tenormichaelk** [comment]
Thanks for responding! Enjoying the game, great way to learn geography with my grandkids!!
