### ISSUE TITLE
Bug: Different countries in different browsers

### ISSUE THREAD

**Issue by robcowen** [teuteuf/worldle#162]
My friends and I have noticed that we are receiving different countries on the same day. I’ve also reproduced this issue on different web browsers. For example, yesterday my friend had Tanzania, whereas I had the USA.

Looking at the code, the most likely cause (I think) is that one of us has an active ‘small country cooldown’ and the other does not, leading to a divergence in our countries.

**Comment by Yiyiyimu** [comment]
The same problem happens here and I believe you are right. It might be a good idea to provide users an API to manually set that parameter so we could stay at the same pace with friends.

**Comment by teuteuf** [comment]
Yep, @Yiyiyimu is right, your browser is not running the last version of the app, that's why you don't see the same pick than most of the other people.

Ctrl+F5 on PC, close and reopen tab a few times on mobile and it should be good. :)

**Comment by teuteuf** [comment]
I did some improvements to improve the cache refresh but... It needs to be refreshed to improve the refresh... 🤪

**Comment by filbo** [comment]
Following here from #198.  I was offered a country outline today which I recognized immediately, since I'd solved it just a few days earlier.  Got it in one guess.  Then I came here searching, found this, and hit Ctrl+F5.

... so now my Wordle tab is in the peculiar state of showing the outline of a **_different_** country, the _name_ of the first country, '0mi' and '100%'.

To be clear:

- a few days ago I solved country 'C1'
- today I got the outline of C1, guessed C1, won in one guess
- then I hit Ctrl+F5
- on reload, I see the outline of _C2_, but the rest of the display reads 'C1 0mi 100%'
- I am not given the opportunity to guess at C2 as I have supposedly already 'solved' it with the guess of C1 (fortunately I recognize C2 on sight so it isn't an interesting target anyway... :)

Is there something different the server could do, protocol-wise, to inform the client that it's out of its mind and ought to refresh its code?  (Or is this entirely client-side with just a cookie / local storage of some sort to remember one's track record?)
