### ISSUE TITLE
BUG - Image doesn't not match answer

### ISSUE THREAD

**Issue by brandonnhem** [teuteuf/worldle#199]
Wordle No. 100's image is Cuba. However, Costa Rica was the correct answer for me. In an attempt to duplicate the bug in incognito mode, entering Costa Rica was incorrect. I've attached my bugged initial attempt's screenshot.
![Screenshot_20220501-191939](https://user-images.githubusercontent.com/27984913/166177464-3c818504-f65b-4e5b-9cc8-279df762250b.png)

**Comment by woctezuma** [comment]
It sounds like the same kind of issue as in:
- https://github.com/teuteuf/worldle/issues/162#issuecomment-1114468840

**Comment by teuteuf** [comment]
Your game was not up to date when it displayed Costa Rica and it validated your input at this moment.
If it displayed Cuba, it means it successfully refreshed the code and you have the new way to pick country to avoid duplicates, but... it keep your initial guess, so it give this weird thing as result...
Good news: you should not have problem anymore because it's updated now!
