### ISSUE TITLE
Moldova served twice within less than 100 days apart

### ISSUE THREAD

**Issue by makmanos** [teuteuf/worldle#263]
I just got served Moldova which was served less than 100 days ago.

**Comment by vitorhugods** [comment]
I'm pretty sure it was 3 days ago, wasn't it?

I haven't looked into the randomisation to see how it works but I'll try something later today.

**Comment by makmanos** [comment]
Yes I have

> I'm pretty sure it was 3 days ago, wasn't it?
> 
> I haven't looked into the randomisation to see how it works but I'll try something later today.

Yes I have an image of it, it was on 6/27.

**Comment by redbmk** [comment]
The latest commit was 7 days ago, but when was the code last deployed? From what I can tell the algorithm thinks that today is the first time Maldova was picked. My hunch is that if the algorithm changed recently, it would think MD was never picked before. You might either need to keep a history of dates countries were picked whenever the logic changes, or keep the old logic for certain date ranges, since it's generating the previously picked countries on the fly.

**Comment by redbmk** [comment]
Just debugging the code currently deployed, it seems to think that Morocco was the country selected on June 27th.

**Comment by teuteuf** [comment]
Yep, there was a problem in the picking algorithm, should be fixed now.

If you're curious, there was a mixup between the currentDayDate et the pickingDate causing trouble.
https://github.com/teuteuf/worldle/commit/1025640675171861aac56d633f3f728ed564434b

Also updated the forced country list to avoid changes to be retroactive and cause more troubles...

**Comment by makmanos** [comment]
> Yep, there was a problem in the picking algorithm, should be fixed now.
> 
> If you're curious, there was a mixup between the currentDayDate et the pickingDate causing trouble. [1025640](https://github.com/teuteuf/worldle/commit/1025640675171861aac56d633f3f728ed564434b)
> 
> Also updated the forced country list to avoid changes to be retroactive and cause more troubles...

Great! Thanks so much! Glad I brought it up.
