### ISSUE TITLE
Macao is not a country

### ISSUE THREAD

**Issue by geonut79** [teuteuf/worldle#295]
It's called "one country, two systems" for a reason.  Both Macao and Hong Kong are part of China, even if the are governed differently.  Perhaps this answer would have worked in 1999, but then it was transferred over to China, and is now part of the People's Republic of China.

**Comment by BOhUiginn** [comment]
As the game says, correct answers are countries or territories. As Macau is a territory of China, it’s a valid answer.

**Comment by geonut79** [comment]
Except it is not a territory, it is a special administrative district within the country of China.  This would be like claiming the District of Columbia is its own territory, as it's not one of the 50 United States.
    On Monday, August 8, 2022, 12:05:04 PM EDT, Brendan OhUiginn ***@***.***> wrote:  
 
 


As the game says, correct answers are countries or territories. As Macau is a territory of China, it’s a valid answer.

**Comment by BOhUiginn** [comment]
Technically the game says "Each guess must be a valid country, territory, ...". 

Macau (and DC for that matter) would fall under the "…".

**Comment by Arb0l** [comment]
In which case as a separate large territory Alaska should be included, plus Hawaii etc. Scotland, Wales and NI, plenty of possibilities under '....'!

**Comment by BOhUiginn** [comment]
By that logic, then each of the Chinese provinces should also be included in the list.

Since Macao and Hong Kong are NOT the same as Chinese provinces. They are counted as special/separate territories. Alaska, Hawaii, etc. are the SAME as all other states in the US, so they shouldn't be included in the list. But, Guam, Puerto Rico, American Samoa, etc should be included. 

For this game, no one is saying Guam isn't part of the US or Macao isn't part of China. But they count as separate territories/regions for the list of possible answers. See how that works?

**Comment by NickSto** [comment]
Both Macao and DC are legally distinct from the rest of their countries, with different rights and administration. It's a judgment call to say that Macao is "different enough" from the rest of China, but DC is not. For whatever reason, that's the decision the [ISO 3166 Maintenance Agency](https://en.wikipedia.org/wiki/ISO_3166#ISO_3166_Maintenance_Agency) made. They're the ones that came up with the standard that Worldle uses.

Technically Worldle could code its own exceptions to ISO 3166, but that would quickly lead to endless political arguments. I guess the clearest thing would be to stop trying to define the political unit Worldle is about and just say it's about ISO 3166 territories, full stop!

**Comment by Arb0l** [comment]
Scotland is a legally different territory with its own distinct laws and currency. The political argument isn’t going to stop unless there’s a consistency that Worldle decides to grasp. Haltingly or not!
________________________________

**Comment by NickSto** [comment]
> Scotland is a legally different territory with its own distinct laws and currency.

True. Even US states technically each have their own laws, so it's really not simple to define what's a "normal" territory and what's an "unusual" one that's considered more autonomous.

> The political argument isn’t going to stop unless there’s a consistency that Worldle decides to grasp.

The consistency is [ISO 3166](https://en.wikipedia.org/wiki/ISO_3166), which is probably as good as you could hope for. I don't think there's any universally-agreed consistency possible, because politics is messy. Shifting the responsibility to ISO 3166 doesn't stop the arguments, but at least it's a way to say "I'm not making the decisions; take it up with them."

**Comment by BOhUiginn** [comment]
I was going to say…
It's smart of the developer to just use the ISO 3166. Have a problem with the definitions? Take it up with International Organization for Standardization (ISO).

The ISO standard defines codes for the names of countries, dependent territories, special areas of geographical interest, and their principal subdivisions (e.g., provinces or states).

I think it's pretty easy to see Macau as a special area of geographical interest. Its geographical interest doesn't diminish any claims of "one country two systems".

**Comment by teuteuf** [comment]
Thank you @NickSto and @BOhUiginn for your answers. It's sum up exactly why I choose to use ISO 3166-1 as source for possible answers.
