### ISSUE TITLE
Israel Borders

### ISSUE THREAD

**Issue by Zionist1948** [teuteuf/worldle#76]
The outline used for the Israeli borders today was from pre 1967, please fix this.

**Comment by Rade-Mathis** [comment]
You are basically asking to consider Golan Heights as a part of Israel, rather than a part of Syria.
As all disputed territories, it's always hard to decide in which country to map them.

The "international community"'s point of view, is that the Golan Heights are part a Syria, but occupied by Israel. This is what the United Nation security council stated in its 242nd resolution[^1], and reaffirmed by its general assembly in 2008[^2].

I personally don't have any opinion about how disputed territories should be mapped though.

[^1]: http://unscr.com/en/resolutions/doc/242)
[^2]: https://www.un.org/press/en/2008/ga10794.doc.htm

**Comment by randomguy213** [comment]
No, he is also asking for the Gaza strip to be considered part of Israel as it is and has been. Since Palestine has not been a country since 1967
