### ISSUE TITLE
Guernsey next to Croatia

### ISSUE THREAD

**Issue by Groganer1** [teuteuf/worldle#90]
Today's worldle had me 93% accurate to Croatia and Slovenia.
![Screenshot_20220311-063429_Chrome](https://user-images.githubusercontent.com/101385557/157815585-6cfae845-a7fa-414a-b9c6-27c8e70d5af4.jpg)

**Comment by Rade-Mathis** [comment]
This is the expected behavior:

Guernsey and Croatia are roughly 1500 km apart.
Earth diameter is roughly 20'000 km.
((20000 - 1500) / 20000) * 100 ≈ 93

Graphically speaking:
![image](https://user-images.githubusercontent.com/10682443/157841675-50fa2d56-1786-4fa0-b048-509bfee869e9.png)
Oppiste side of the world is 0%, Guernsey island is 100%. By trying Croatia, you've already done 93% of the distance from the opposite side of the world, only 7 to go.

**Comment by teuteuf** [comment]
Thanks @Rade-Mathis for the explanation! <3
It's completely right!

**Comment by Groganer1** [comment]
Perfect, thank you! I'm new to the game and country locations so my perception of distance is fairly inaccurate. 

Onwards and upwards!
