### ISSUE TITLE
Guernsey

### ISSUE THREAD

**Issue by Tricky330** [teuteuf/worldle#95]
Guernsey is an island in the Channel Islands, which is part of the United Kingdom, therefore it is not a country or a territory.

**Comment by teuteuf** [comment]
That's why it's asking for "Country, territory, ...", the "..." corresponds to this kind of cases.

I use ISO 3166-1 as country code list and it's in the list. That's why it has been randomly picked today.

**Comment by gtdeng** [comment]
@teuteuf Thanks for using the ISO-3166-1 standard and including Guernsey; I wouldn't have known about this standard if you didn't include it in your FAQs.

@Tricky330 Here's a list of all the "places" included in the standard: https://en.wikipedia.org/wiki/ISO_3166-1 , which includes Guernsey.

**Comment by ianlost** [comment]
Guernsey was highly misleading because the image also showed Alderney, Sark, and other minor islands in the group (but not Jersey). Showing a random selection of islands and using only one of them as the answer is messy.
Also, Perhaps you should provide a more accurate description of what areas may constitute a valid answer, as ‘Country, territory, …’ is too vague.
