### ISSUE TITLE
Be Accurate and don't provide a location that is not a recognized country!!!

### ISSUE THREAD

**Issue by bsegafredo** [teuteuf/worldle#99]
This is the second time in the last few weeks that they location shown is not a country! Today's choice of Guernsey and then the British Indian Ocean Territory a week or so ago.  Both are just protectorates of the UK, they are not countries.  Please update your game to only include actual countries.  I really enjoy the game, but many more times of errors like this and I'm done.

**Comment by Tiv0w** [comment]
Every puzzle choice is taken from the [ISO_3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) list. This includes not only countries but also some territories.
If you click the interrogation mark, you'll see that "each guess must be a valid **country, territory, ...**". Plus the input box clearly indicates that the guess could be a territory.

I'm sorry but this game exactly provides what it advertises for.

As a personal note, I'd argue that it's for the better, because it helps you learn about new things. If you want to create COUNTRYDLE, go for it, or you could also propose a PR with the possibility to only have the UN recognized countries.

**Comment by bsegafredo** [comment]
I would argue that its not clear that this can incorporate places other than countries.  If that's going to be the case, then can you make it more obvious, perhaps as a sub title, or a better explanation in the directions.  As it is now, its vague at best. 

As part two of that, where do you draw the line. I've noticed that the territories in the UK are not options (Scotland, Wales).  How those any different than Guernsey or British Indian Ocean Territory? (Short answer is they are not). 

I'm honestly making these complaints and suggestions to make your game better.  I love Geography, so its very frustrating when there is minutia and nuances in some ways, but not in the others.
